[package]
name = "mintmark"
version = "0.1.0"
authors = ["Benjamin Gilbert <bgilbert@backtick.net>"]
edition = "2018"

[dependencies]
barcoders = "1.0.1"
bitflags = "1.2.1"
encoding = "0.2.33"
image = { version = "0.23.0", default-features = false }
pulldown-cmark = "0.6.1"
qrcode = { version = "0.11", default-features = false }
