[package]
name = "mintmark"
version = "0.2.0"
authors = ["Benjamin Gilbert <bgilbert@backtick.net>"]
edition = "2018"
license = "Apache-2.0"
description = "Markdown renderer for Epson TM-U220B receipt printers"
readme = "README.md"
repository = "https://github.com/bgilbert/mintmark"
exclude = [
    ".gitignore",
    ".travis.yml"
]

[dependencies]
barcoders = "1.0.1"
bitflags = "1.2.1"
clap = "2.33.1"
encoding = "0.2.33"
fs2 = "0.4.3"
image = { version = "0.23.4", default-features = false }
pulldown-cmark = "0.7.1"
qrcode = { version = "0.12", default-features = false }
