name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  PINNED_TOOLCHAIN: 1.49.0

jobs:
  test:
    strategy:
      matrix:
        rust:
          - ${{ env.PINNED_TOOLCHAIN }}
          - stable
          - beta
        experimental: [false]
        include:
          - rust: nightly
            experimental: true
    name: Tests (${{ matrix.rust }})
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
          default: true
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test --verbose --all
      - name: rustfmt check
        run: cargo fmt -- --check -l
        if: ${{ matrix.rust }} == ${{ env.PINNED_TOOLCHAIN }}
      - name: Clippy
        run: cargo clippy -- -D warnings
        if: ${{ matrix.rust }} == ${{ env.PINNED_TOOLCHAIN }}
